
export const data = [
  {
    id: 1,
    src: "/Assets/Images/imageProduct/product-1.png",
    name: "GKH AKM GBBR",
    code: "AKM",
    weight: "3100g",
    long: "900mm",
    price: 1000000,
    material: "Kim loại, Gỗ, Thép",
    use: "Gas",
    power: "350-380 fps (0.20g)",
    BlowBack:	"Có",
    HopUp:	"Có",
    FiringMode: "Semi, Full Auto",
    SafeMode: "Có",
    AmmoTapes: "50",
    ammo: "6mm BBs",
    manufacturer: "GHK Made in Taiwan",
    quantity: 1,
    status: true,
    type: "Súng Trường Dùng Gas"
  },
  {
    id: 2,
    src: "/Assets/Images/imageProduct/product-2.png",
    name: "M4 RIS CQB Open Bolt GBBR",
    code: "M4 RIS CQB",
    weight: "3100g",
    long: "772-854mm",
    price: 2000000,
    material: "Kim loại, Thép",
    use: "Gas",
    power: "440 fps (0.20g)",
    BlowBack:	"Có",
    HopUp:	"Có",
    FiringMode: "Semi, Full Auto",
    SafeMode: "Có",
    AmmoTapes: "30",
    ammo: "6mm BBs",
    manufacturer: "WE Tech",
    quantity: 1,
    status: true,
    type: "Súng Trường Dùng Gas"
  },
  {
    id: 3,
    src: "/Assets/Images/imageProduct/product-3.png",
    name: "FN SCAR H GBBR – TAN (by VFC)",
    code: "CY-200550",
    weight: "4344g",
    long: "625mm",
    price: 3000000,
    material: "Kim loại, Thép",
    use: "Green Gas / Top Gas",
    power: "390 fps (0.20g)",
    BlowBack:	"Có",
    HopUp:	"chỉnh được",
    FiringMode: "Semi, Full Auto",
    SafeMode: "Có",
    AmmoTapes: "24",
    ammo: "6mm BBs",
    manufacturer: "Cybergun",
    quantity: 1,
    status: true,
    type: "Súng Trường Dùng Gas"
  },
  {
    id: 4,
    src: "/Assets/Images/imageProduct/product-4.png",
    name: "HK416D CAG Full Marking GBBR",
    code: "HK 416 D CAG",
    weight: "2950g",
    long: "713-797mm",
    price: 4000000,
    material: "Kim loại, Nhựa",
    use: "Green Gas / Top Gas",
    power: "400 fps (1.47 Joules)",
    BlowBack:	"Có",
    HopUp:	"chỉnh được",
    FiringMode: "Semi, Full Auto",
    SafeMode: "Có",
    AmmoTapes: "30",
    ammo: "6mm BBs",
    manufacturer: "Umarex",
    quantity: 1,
    status: true,
    type: "Súng Trường Dùng Gas"
  },
  {
    id: 5,
    src: "/Assets/Images/imageProduct/product-5.png",
    name: "Beretta M92 Black",
    code: "M92",
    weight: "1050g",
    long: "215mm",
    price: 5000000,
    material: "Kim loại, Nhựa",
    use: "Green Gas / Top Gas",
    power: "350 fps (0.20g)",
    BlowBack:	"Có",
    HopUp:	"chỉnh được",
    FiringMode: "Semi Auto",
    SafeMode: "Có",
    AmmoTapes: "25",
    ammo: "6mm BBs",
    manufacturer: "WE Tech",
    quantity: 1,
    status: true,
    type: "Súng Ngắn"
  },
  {
    id: 6,
    src: "/Assets/Images/imageProduct/product-6.png",
    name: "AR15 SWORD AT-AR08 Full Metal",
    code: "AT-AR08",
    weight: "2380g",
    long: "605-670mm",
    price: 6000000,
    material: "Kim loại",
    use: "Dùng Điện",
    power: "410fps với bb 0,20g",
    BlowBack:	"Không Có",
    HopUp:	"Có (Quay)",
    FiringMode: "Semi / Full-Auto",
    SafeMode: "Có",
    AmmoTapes: "30-130 / 300 bb.",
    ammo: "6mm",
    manufacturer: "ARCTURUS",
    quantity: 1,
    status: true,
    type: "Súng Trường Dùng Điện"
  },
  {
    id: 7,
    src: "/Assets/Images/imageProduct/product-7.png",
    name: "HK417 GBBR",
    code: "KWA-417-G",
    weight: "3,980g",
    long: "840mm",
    price: 7000000,
    material: "Kim loại",
    use: "Green Gas / Top Gas",
    power: "400 fps (1.47 Joules)",
    BlowBack:	"Có",
    HopUp:	"Có (Quay)",
    FiringMode: "Semi Auto / Full Auto",
    SafeMode: "Có",
    AmmoTapes: "20 rds",
    ammo: "6mm",
    manufacturer: "ARCTURUS",
    quantity: 1,
    status: true,
    type: "Súng Bắn Tỉa"
  },
  {
    id: 8,
    src: "/Assets/Images/imageProduct/product-8.png",
    name: "Thompson CHICAGO EBBR",
    code: "Thompson CHICAGO",
    weight: "3860g",
    long: "880mm",
    price: 8000000,
    material: "Gỗ, kim loại",
    use: "Green Gas / Top Gas",
    power: "380 (0.20g)",
    BlowBack:	"Có",
    HopUp:	"Có (Quay)",
    FiringMode: "Semi Auto / Full Auto",
    SafeMode: "Có",
    AmmoTapes: "100bb",
    ammo: "6mm BBs",
    manufacturer: "ARES",
    quantity: 1,
    status: true,
    type: "Súng Cổ"
  },
  {
    id: 9,
    src: "/Assets/Images/imageProduct/product-8.png",
    name: "Thompson CHICAGO EBBR",
    code: "Thompson CHICAGO",
    weight: "3860g",
    long: "880mm",
    price: 8000000,
    material: "Gỗ, kim loại",
    use: "Green Gas / Top Gas",
    power: "380 (0.20g)",
    BlowBack:	"Có",
    HopUp:	"Có (Quay)",
    FiringMode: "Semi Auto / Full Auto",
    SafeMode: "Có",
    AmmoTapes: "100bb",
    ammo: "6mm BBs",
    manufacturer: "ARES",
    quantity: 1,
    status: true,
    type: "Súng Cổ"
  },
  {
    id: 10,
    src: "/Assets/Images/imageProduct/product-8.png",
    name: "Thompson CHICAGO EBBR",
    code: "Thompson CHICAGO",
    weight: "3860g",
    long: "880mm",
    price: 8000000,
    material: "Gỗ, kim loại",
    use: "Green Gas / Top Gas",
    power: "380 (0.20g)",
    BlowBack:	"Có",
    HopUp:	"Có (Quay)",
    FiringMode: "Semi Auto / Full Auto",
    SafeMode: "Có",
    AmmoTapes: "100bb",
    ammo: "6mm BBs",
    manufacturer: "ARES",
    quantity: 1,
    status: true,
    type: "Súng Cổ"
  },
]