export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const HANDLE_CHANGE_STATUS = 'HANDLE_CHANGE_STATUS';
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART';
export const HANDLE_INCREASE_QUANTITY = "HANDLE_INCREASE_QUANTITY";
export const HANDLE_DECREASE_QUANTITY = "HANDLE_DECREASE_QUANTITY";